[package]
name = "checksum"
version = "0.1.0"
edition = "2021"

[dependencies]
data-encoding = "2"
ring = "0.17"
serde = { version = "=1.0.210", features = ["derive"] }
serde_json = "1"
thiserror = "1"
walkdir = "2"

[dev-dependencies]
tempfile = "3"