[package]
name = "crate-updater"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.4.6", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"
serde = { version = "=1.0.210", features = ["derive"] }
serde_json = "1"
