[package]
name = "license_checker"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3"
itertools = "0.14"
spdx = "0.10"
textdistance = "1.1.1"
thiserror = "1.0"
google_metadata = { path = "../google_metadata"}