[package]
name = "crates_io_util"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-expr = "0.17"
crates-index = "3.2.0"
ureq = "3"
semver = "1"
thiserror = "1"

[dev-dependencies]
serde_json = "1"
itertools = "0.11"
