LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE := true
LOCAL_MODULE := AdbWinApi
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_SRC_FILES_x86 := AdbWinApi.a
LOCAL_MODULE_SUFFIX := .a
LOCAL_MULTILIB := 32
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE := true
LOCAL_MODULE := AdbWinApi
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES_x86 := AdbWinApi.dll
LOCAL_MODULE_SUFFIX := .dll
LOCAL_MULTILIB := 32
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE := true
LOCAL_MODULE := AdbWinUsbApi
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES_x86 := AdbWinUsbApi.dll
LOCAL_MODULE_SUFFIX := .dll
LOCAL_MULTILIB := 32
include $(BUILD_PREBUILT)
