#!/bin/bash
# Copyright (C) 2018 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Get the pid of processes matching a string.
EXACT=0
if [ "$1" = "--exact" ]; then
    EXACT=1
    shift
fi

EXE="$1"
if ! [ "$EXE" ] ; then
    echo "usage: pid [--exact] <process name>"
    exit 255
fi

if [ $EXACT == 1 ]; then
    PIDS="$(adb shell pidof $EXE)"
else
    PIDS="$(adb shell pgrep -f $EXE)"
fi
RC=$?

for PID in $PIDS; do
    echo $PID
done

exit $RC
