[package]
name = "repo_config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "=1.0.210", features = ["derive"] }
toml = "0.8"
thiserror = "1.0"

[dev-dependencies]
tempfile = "3"